apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: 8byte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: 8byte-catalog:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: 8byte-config
                  key: NODE_ENV
            - name: PORT
              value: "3001"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: 8byte-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: 8byte-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: 8byte-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: 8byte-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: 8byte-secrets
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: 8byte-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: 8byte-config
                  key: REDIS_PORT
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: 8byte-config
                  key: REDIS_URL
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: 8byte-config
                  key: RABBITMQ_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: 8byte
spec:
  selector:
    app: catalog
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
